### ISSUE TITLE
Store title with timer, and print it

### ISSUE THREAD

**Issue by krlmlr** [poissonconsulting/hmstimer#11]
The title could be a user-specified string, and/or the source location of the call that created the timer. The latter could be obtained via

```r
  caller <- sys.call()
  srcref <- utils::getSrcref(caller)
  file <- utils::getSrcFilename(caller)
  file_line <- paste0(file, ":", srcref[[1]])
```

(the above code has no error checking).

The title would be printed every time the timer is printed, this could be turned off.

**Comment by joethorley** [comment]
@krlmlr - see pull request

**Comment by krlmlr** [comment]
Usage, now that we have `local_timer()` :

```r
local_timer("message")
#> +00:00:00 message
local_timer(srcref = TRUE)
#>  +00:00:00 fileR:1
#>  -00:00:00 file.R:1
#> -message 00:00:00
```

The indent would also be nice to have, but is unrelated here.
