### ISSUE TITLE
local_tmr()

### ISSUE THREAD

**Issue by krlmlr** [poissonconsulting/hmstimer#12]
New function that wraps `tmr_timer(start = TRUE)` and shows the elapsed time when started and on exit (via `withr::defer()`). Useful for adding trace messages for debugging, in combination with #11.

**Comment by joethorley** [comment]
Very interesting - do you want to spend sometime on this together when we are working this fall or do you want us to take a stab before?

**Comment by krlmlr** [comment]
Either way works for me. For reference, here's my own `local_timer()` that also shows the caller's location.

```r
local_timer <- function(title = NULL, frame = rlang::caller_env()) {
  caller <- sys.call()
  srcref <- utils::getSrcref(caller)
  file <- utils::getSrcFilename(caller)
  file_line <- paste0(file, ":", srcref[[1]])

  if (is.null(title)) {
    title <- file_line
  } else {
    title <- paste0(file_line, ": ", title)
  }

  tmr <- hmstimer::tmr_timer(start = TRUE)
  message(title)
  withr::defer(message(title, ": ", format(hmstimer::tmr_elapsed(tmr))), frame)

  tmr
}
```
