### ISSUE TITLE
add tmr_print() for timer specific printing

### ISSUE THREAD

**Issue by joethorley** [poissonconsulting/hmstimer#6]
`tmr_print(t)` -> `12:34:56 (+00:01:23 => 12:36:19)`

**Comment by krlmlr** [comment]
Is this done now?

**Comment by joethorley** [comment]
Yes we just need to close the issue and send to CRAN. If you have time to check it out we'd be interested to hear your thoughts.

**Comment by krlmlr** [comment]
Thanks. I don't want to block the CRAN release, we can release again after a week if needed 🙃 

I'll come back here over the next few months.
